"""stat table

Revision ID: 98c4dedfa158
Revises: ab0b1e6f6cb5
Create Date: 2025-02-13 22:15:32.826077

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '98c4dedfa158'
down_revision: Union[str, None] = 'ab0b1e6f6cb5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('url', sa.Column('count', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('url', 'count')
    # ### end Alembic commands ###
