"""user info

Revision ID: a0eb959c8d65
Revises: fbbd2ac9a703
Create Date: 2025-02-13 23:17:19.839440

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a0eb959c8d65'
down_revision: Union[str, None] = 'fbbd2ac9a703'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('url', sa.Column('created_by_ip', sa.String(), nullable=False))
    op.add_column('url', sa.Column('created_by_agent', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('url', 'created_by_agent')
    op.drop_column('url', 'created_by_ip')
    # ### end Alembic commands ###
