"""unique url

Revision ID: fbbd2ac9a703
Revises: 98c4dedfa158
Create Date: 2025-02-13 22:54:48.470569

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fbbd2ac9a703'
down_revision: Union[str, None] = '98c4dedfa158'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'url', ['url'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'url', type_='unique')
    # ### end Alembic commands ###
